import BackgroundVid from "@/components/BackgroundVid";
import { useUserData } from "@/libs/providers/UserContext";
import { CenterBox } from "@/src/styles";
import {
  AreaCardWrapper,
  ArenaCard,
  ArenaPaddingWrap,
  ArenaTitleText,
} from "@/src/styles/Arena";
import { Box, Container } from "@chakra-ui/react";
import Head from "next/head";

export default function Settings() {
  const { state } = useUserData();

  return (
    <>
      <Head>
        <title>Settings - Endgame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundVid
        mp4={state.settings.video_bg.mp4}
        webm={state.settings.video_bg.webm}
      />

      <Box position="relative" h="calc(100vh - 90px)" w="100%">
        <CenterBox>
          <Container maxW="container.xl" minW="1200px">
            <ArenaCard>
              <AreaCardWrapper widthgap="95%">
                <ArenaPaddingWrap>
                  <ArenaTitleText>Settings</ArenaTitleText>
                </ArenaPaddingWrap>
              </AreaCardWrapper>
            </ArenaCard>
          </Container>
        </CenterBox>
      </Box>
    </>
  );
}
