import Head from "next/head";
import { useUserData } from "@/libs/providers/UserContext";
import BackgroundVid from "@/components/BackgroundVid";

export default function Home() {
  const { state } = useUserData();
  return (
    <>
      <Head>
        <title>Endgame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundVid
        mp4={state.settings.video_bg.mp4}
        webm={state.settings.video_bg.webm}
      />
    </>
  );
}
