import Head from "next/head";
import { BackgroundEGVideo, BackgroundEGWrapper } from "@/src/styles";
import { useUserData } from "@/libs/providers/UserContext";

export default function Home() {
  const { state } = useUserData();
  return (
    <>
      <Head>
        <title>Endgame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundEGWrapper>
        <BackgroundEGVideo autoPlay loop muted preload="auto">
          <source type="video/mp4" src={state.settings.video_bg.mp4} />
          <source type="video/webm" src={state.settings.video_bg.webm} />
        </BackgroundEGVideo>
      </BackgroundEGWrapper>
    </>
  );
}
